### PR TITLE
phiche/openwhisper

### PR DESCRIPTION
**Pull request by philbert**
Added Instant Messaging and Calling apps from OpenWhisper Systems. These apps are FOSS and compatible with one another across iOS and Android.

For iOS: 
Signal (Instant Messaging)

For Android:
RedPhone (Video & Voice)
TextSecure (Instant Messaging)

### CODE REVIEW

**Comment by phiche** [comment]
Submitted this before seeing all of the other PRs, discussions and debates about the apps.
Not including is seems overly dogmatic to me, and not very helpful to the average user. 
Using these any of these apps is a significant improvement to security over the standard messaging/voice in Android and iOS.

**Comment by TheMSB** [comment]
@phiche These apps have already been discussed and been referenced in their own individual pull requests. I suggest that you continue the discussion about each specific one in their own PR. Especially Redphone and Textsecure have not been included for specific reasons and as such it is doubtful they will be added with the current format.

**Comment by Klimmbimmel** [comment]
Discussion here: #1314

**Comment by strugee** [comment]
Closing since even if we add these projects this has merge conflicts and references outdated names.

Thanks for contributing to PRISM Break!

**Pull request closed without merging**
