### PR TITLE
Add Signal

### PR DESCRIPTION
**Pull request by rZsnWwM5**
I think Signal can now be added to Prism-Break since it is officially Google-free. So far, the main reason for why Signal hasn't been added to Prism-Break has been the Android client's dependency on Google Play Services. Before February 20, people had to either have Google Play or microG on their phone for Signal to be fully functional, and before March 13, people had to compile the app themselves if they wanted to install it on a device that didn't include Google Play. Signal is no longer dependent on the GCM push messaging framework, and the Android client can now officially be downloaded and installed from outside of the Google Play Store: https://signal.org/android/apk/

There has also been some discussion about Signal's voice calling component's backend not being open source. This discussion is now obsolete, because Signal has completed the transition from RedPhone to WebRTC. Signal's backend is now fully open source: https://github.com/whispersystems

For reference:
https://github.com/WhisperSystems/Signal-Android/commit/ea0945d406bae68df88b7351148b269e386fd9b2
https://github.com/WhisperSystems/Signal-Android/commit/1669731329bcc32c84e33035a67a2fc22444c24b
https://github.com/WhisperSystems/Signal-Android/commit/9b8719e2d56a098502475bb5b2295c7a376d4caa
https://whispersystems.org/blog/signal-video-calls-beta/
https://whispersystems.org/blog/signal-video-calls/

This pull request closes:
https://github.com/nylira/prism-break/issues/1314
https://github.com/nylira/prism-break/pull/1392
https://github.com/nylira/prism-break/pull/1127
https://github.com/nylira/prism-break/issues/1239

Edit: I realize that these commits probably need to be [squashed](https://github.com/blog/2141-squash-your-commits). That's unfortunately beyond of my skill set.
Edit 2: In case people are wondering whether signal.org is official or someone else pretending to be them, they've confirmed on Twitter that [it's official](https://twitter.com/whispersystems/status/841464636532641792).

### CODE REVIEW

**Comment by alerque** [comment]
Thanks for working on getting this added. Yes these need to be squashed, but more importantly a lot of these actually shouldn't be included. Only the EN resources need updating unless you are explicitly translating. Putting EN strings in the other language files has been obsoleted by them being automatically included where no translation exists.

Unfortunately I don't have access to fix this for you. What git client and platform are you using? I can probably help walk you through it.

**Comment by rZsnWwM5** [comment]
Thanks for pointing that out. I have now removed or replaced the EN strings in the other language files.

I'm on a Mac, using GitHub Desktop + Terminal. I got as far as `git rebase -i HEAD~84` and replacing "pick" on the second and subsequent commits with "s" and opening a second terminal to run `git rebase --continue`, but then I got an error saying "could not apply 6fb1d54".

**Comment by rZsnWwM5** [comment]
I was able to combine everything into this one commit: https://github.com/nylira/prism-break/pull/1711/commits/baa233c1f6d2ffb61f45499ca236bd178d37b509

**Comment by hasufell** [comment]
174 commits? I suggest http://shafiulazam.com/gitbook/index.html

**Comment by rZsnWwM5** [comment]
@hasufell Thanks, I'll look into that. :) I found some info about squashing on stackoverflow, but as you can see, that didn't get me very far. I thought that I'd combine everything into one commit and let someone cherry pick it (if that's possible).

**Comment by rZsnWwM5** [comment]
Closed this PR and opened https://github.com/nylira/prism-break/pull/1713 because I couldn't get the commits squashed properly.

**Pull request closed without merging**
