### PR TITLE
Add Monero Currency

### PR DESCRIPTION
**Pull request by khantahirx**
I Have Added A New Cryptocurrency Called Monero Which Unlike Bitcoin Is More Private And Untraceable Currency. Monero Was Coded From Beginning And Is Not A Fork Of Bitcoin Like Any Other Altcoin. Here Are Some Of The Features Of Monero Which Surpass The Privacy Of Bitcoin.

1) Monero's Blockchain Is Not Public, So Unlike Bitcoin, You Cant See The Balance And Transaction Of A Wallet, Hence Untraceable.
2) Monero Has Built-In Mixers (Aka Coin Mixer) Which Make It Untraceable.
3) Monero Is Going To Ringct, A Feature In Which A Transactions Amount Can Not Be Sent.
4) Monero Has A Stealth Wallet Address Feature In Which You Do Not Have To Create Multiple Addresses.

So In Bitcoin Your Privacy Can Be Comprised By A Technique Called "Blockchain Analysis", Which Can Link Your Transactions And Might Even Find Out Where You Use Your Money Or Which Person Withdrew It.

### CODE REVIEW

**Comment by fluffypony** [comment]
I'm the lead maintainer of the Monero project, and it would be my privilege and honour to assist in refining this PR so that it is merged. Please note that the Monero project consists of more than just the Monero pro-privacy cryptocurrency; other projects of interest include [Kovri](https://github.com/monero-project/kovri), an i2p router written in C++.

**Comment by khantahirx** [comment]
Hey fluffypony, i thought to add monero this site so that people can benefit from it, good to see that you found this out and made a comment on it. Did i correctly write the description for it?

**Comment by nylira** [comment]
Hey there. Please add the JSON data for Monero to all the other language files too. Everything else looks in order. Thanks!

**Comment by vyp** [comment]
No worries, I added them! Thank you @khantahirx for the pull request and thank you @fluffypony for Monero!

**Pull request merged**
