### PR TITLE
Updates Tox website URL

### PR DESCRIPTION
**Pull request by gutobenn**

### CODE REVIEW

**Comment by Zegnat** [comment]
That sure did sound like drama… accepting change in domain based on these two blog articles:

* [Current Situation](https://blog.tox.chat/2015/07/current-situation-3/) (Tox development team, `tox.chat`)
* [Tox infastructure and various changes](https://blog.tox.im/2015/07/09/tox-infa-update/) (Tox Foundation, `tox.im`)

**Comment by vyp** [comment]
Should there be a note about warning that tox.im being potentially unsafe? https://blog.tox.chat/2015/07/current-situation-3/#comment-14

@Zegnat's second link is broken for me: http://webcache.googleusercontent.com/search?q=cache%3Ahttp%3A%2F%2Fcache.nevkontakte.com%2Fproxy.html#!go/https%3A%2F%2Fblog.tox.im%2F2015%2F07%2F09%2Ftox-infa-update%2F

**Comment by Zegnat** [comment]
Seems the `tox.im` domain is just… gone now? In between me checking this pull and @vyp looking into it. Weird things happening. I wonder if we should temporarily suspend Tox from the list ’til things have settled?

**Comment by vyp** [comment]
If you mean the drama, that's already settled as much as it ever will. (I think, I don't know about anything that still might be happening behind the scenes of course.) I actually first learnt about this late 2014 iirc but I'm not sure if that was when it started, I think it was earlier than that. As for the site's stability, my opinion is that the new tox.chat should be fine, really.

**Pull request merged**
