### PR TITLE
Lithuanian translation

### PR DESCRIPTION
**Pull request by techwebpd**
i translated into lithuanian

### CODE REVIEW

**Comment by Zegnat** [comment]
I think we would need [DB language files](https://github.com/nylira/prism-break/tree/master/source/db) for Lithuanian too, before this would be useful to merge. Will you also be working on those, @techwebpd?

**Comment by techwebpd** [comment]
i will

**Comment by Zegnat** [comment]
Nice.

Just so you know, I will hold off on merging until all language files are there, to keep build problems at bay.

**Comment by strugee** [comment]
@techwebpd ping? WIll you be able to add the additional data?

**Comment by yegortimoshenko** [comment]
This has been based off Russian translation and is quite stale at this point. That said, it is still worth merging to ease translation for someone who will work on adding Lithuanian locale to PRISM Break in the future. It isn't hooked up to any of the build files, so it should be harmless.

**Comment by yegortimoshenko** [comment]
Superseded by #1945.

**Pull request closed without merging**
