### PR TITLE
Os cleanup

### PR DESCRIPTION
**Pull request by hasufell**
It also contains more changes than the ones discussed in #1709, however, ArkOS removal should definitely be done.

Since the translations are an utter mess, I didn't change any of those, because I'm not a monkey.

### CODE REVIEW

**Comment by hasufell** [comment]
> It seems really unfortunate that the translated versions will recommend stuff the canonical English version doesn't...

Well, one can't have everything in life!

**Comment by strugee** [comment]
@hasufell mind if I push a commit or two to your branch finishing this?

**Comment by hasufell** [comment]
> @hasufell mind if I push a commit or two to your branch finishing this?

Why? Push it to this repo.

**Comment by alerque** [comment]
> Why?

Because it's a cleaner development cycle and easier to for others to audit. Making all the changes relevant to a discussion in a branch before merging means the commit points on master should reflect the state of discussion on issues & PR's.

> Push it to this repo.

That workflow would merge things to master that are specifically already noted as problematic in the PR review process and require subsequent fixes, also committed to master. This won't matter to everybody but it matters to people like me who step through the changes periodically making sure everything is copasetic, updating translations, etc. PR merges are much easier to review when they are self contained and reflect everything that went into the respective discussion.

**Comment by hasufell** [comment]
> Because it's a cleaner development cycle and easier to for others to audit.

No, that's not how git was intended. He can send me a pull request and once I push it, it will appear here. I'm not giving others full access to my fork.

Or...

> That workflow would merge things to master

I didn't say master. Alternatively he can close this PR, use my commits and make a new PR or push to a wip branch.

**Comment by alerque** [comment]
> I'm not giving others full access to my fork.

Nobody is suggesting that.

Github allows project collaborators to edit branches that are part of PR requests on their projects. In otherwords unless you've removed the  checkbox for that on this PR, @strugee already has access to this branch and was just asking as a courtesy. Alternatively he could checkout the branch locally, make his changes, and merge it separately from this PR, but then the Github PR tracking gets a little funky. Doing it directly on the branch that's already configured as the base for the PR makes the most sense.

**Comment by hasufell** [comment]
> Github allows project collaborators to edit branches that are part of PR requests on their projects.

Didn't notice when this misfeature was added. Usually I wouldn't allow that, but this is trivial enough that I don't care. So go ahead.

**Comment by soredake** [comment]
>gentoo removed
Sad.

**Comment by hasufell** [comment]
> Sad.

Low usability, not for regular users, not even security focused.

The only pro-argument I would get is the [Gentoo Hardened Project](https://wiki.gentoo.org/wiki/Project:Hardened), but that is mostly just _documentation_ and not really a Gentoo specific thing per se (except that you kind of need a source distro to properly do that).

**Comment by soredake** [comment]
>Low usability

For me, for example, the usability is much more than in any debian-based or anything else.

>not for regular users

I am regular user.

**Comment by hasufell** [comment]
@soredake prism-break is a list of privacy-aware alternatives to proprietary software. As such we expect people (like windows users) to look for reasonable alternatives. Recommending Gentoo here is pretty far fetched, actually. This isn't a list of "awesome free software".

**Comment by soredake** [comment]
@hasufell I was a windows user before the transition. I would instead move gentoo to a separate column and call it something like 'advanced alternatives', but that's so, my opinion.

**Comment by hasufell** [comment]
> I was a windows user before the transition.

That's basically the first time I hear that.

Why gentoo is not a useful recommendation for beginners:

* installation is manual
* huge configuration complexity, especially after introduction of REQUIRED_USE
* the "official" PM doesn't follow its own specification and has serious bugs and underspecified features (like preserve-libs) and users have to work around those quirks and oddities quite often
* on blockers and depgraph issues, the error messages are incredibly hard to digest for non-developers
* source-based: while that is a plus to some degree, users cannot really opt-out like they can on FreeBSD, because there's no official binhost (and btw, the binary package format in gentoo is totally _unspecified_)
* updating is often a mess, because QA has to reverse-fix depgraph/eclass/toolchain breakage and whatnot, since gentoo has no enforced review-workflow
* ...

Gentoo has its perks, but it was never intended for beginners. Nor does the community care to improve beginner friendliness (which is ok, it's a decision about where the effort goes).

**Comment by soredake** [comment]
>huge configuration complexity

I did not notice this, it's much more convenient than in other distributions, to my opinion.

>users have to work around those quirks and oddities quite often

This has never happened to me.

>updating is often a mess

3 years without breakages for me, what am i doing wrong?

>but it was never intended for beginners

I can partly agree with this, therefore I proposed a separate category "Free recomendations not for beginners".
Like this:
png

But, this is your pull-request, it's up to you, I just want the choice to be from different systems, both for beginners, and for advanced and experienced.

**Comment by hasufell** [comment]
> I can partly agree with this, therefore I proposed a separate category "Free recomendations not for beginners".

That's a different issue imo and can be discussed and done separately. Similar things have been proposed before on various occasions, so it will probably require more discussion.

**Comment by strugee** [comment]
Finally went through and spent some time doing all this. This LGTM now but I'd appreciate a second set of eyes - if no one says they'll take a look, I'll eventually just merge this as-is.

**Comment by strugee** [comment]
Just pushed some typo fixes because (_\*sigh\*_) the tool I used to validate them... didn't

**Comment by Zegnat** [comment]
For what it is worth, looks good to me. The OS section clean-up has been pending way too long.

**Comment by strugee** [comment]
@Zegnat great, thanks for taking a look. I'll merge then.

**Comment by mimi89999** [comment]
I understand why Debian and Fedora are listed, but where is the explanation about CentOS, FreeBSD and OpenBSD?

**Comment by hasufell** [comment]
> CentOS

Might have been an oversight. I argued for removal, but one could argue it's more server-ish than Fedora, which is why it has the "server" tag.

> FreeBSD

FreeBSD is the biggest *BSD out there, that you could consider "user friendly". It's just natural to list it as the most popular alternative to Linux distros.

> OpenBSD

I argued for removal, but OpenBSD has shown some exceptional dedication to OS security (e.g. the LibreSSL fork), so there is that.

**Pull request merged**
