### PR TITLE
Update Kontalk logo

### PR DESCRIPTION
**Pull request by daniele-athome**
Signed-off-by: Daniele Ricci <daniele.athome@gmail.com>

### CODE REVIEW

**Comment by vyp** [comment]
New logo looks good, thank you!

**Comment by daniele-athome** [comment]
Thanks for merging! Is the live site updated automatically after some time?

**Comment by vyp** [comment]
No, it is manually updated by @nylira.

**Comment by strugee** [comment]
@vyp really? I was under the impression that @nylira had it on a cronjob

**Comment by vyp** [comment]
It's what I knew from way before, but in that time @nylira may have started using a cronjob so maybe I'm wrong. :/

**Pull request merged**
