### PR TITLE
Add Seafile to list of cloud file system replacements

### PR DESCRIPTION
**Pull request by chuyskywalker**
These guys make an amazing project and it has, to date, satisfied everything I wanted out of Dropbox -- but under my control.

### CODE REVIEW

**Comment by pietsch** [comment]
This discussion has become increasingly illogical. Lots of software has an enterprise edition, but people use the Free community edition happily and successfully (see e.g. GitLab). I am not connected in any way to Seafile the company, but I have installed and used the community edition and can say that it is the best replacement for Dropbox I have tried.

**Comment by Zegnat** [comment]
@pietsch, this might be an interesting discussion to reopen (ping @nylira). Last time I looked at Seafile they didn’t even have their terms written up. Now they have a full documentation on [setting up Seafile from source](http://manual.seafile.com/build_seafile/server.html), linking to GPL & Apache licensed GitHub repositories. That looks completely fine to me.

**Comment by patcon** [comment]
+1 @Zegnat https://github.com/nylira/prism-break/pull/123#issuecomment-43247500

**Comment by Sigmun** [comment]
One up !

**Comment by annonman** [comment]
Big fan of the self-hosted project!

**Comment by Sigmun** [comment]
Hi there,
does any expert of you can have a deep look on this ? I am about to open my self-hosted seafile server to my family and friends !

**Pull request merged**
