### PR TITLE
Update Cryptocat.

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by Zegnat** [comment]
Could you trim the whitespace from the images? The `development_stage` should be set to `experimental`, as this is marked a beta release.

Could you do those changes before I merge?

**Comment by mimi89999** [comment]
Yes. I am working on this now.

**Comment by mimi89999** [comment]
@Zegnat I don't see any whitespace in the icons.

**Comment by mimi89999** [comment]
@Zegnat I updated my commit and changed `"development_stage":` to `"experimental"`.

**Comment by mimi89999** [comment]
Ah... I see... The 2px frame, I will remove it.

**Comment by Zegnat** [comment]
We would like the icons to sit flush. You could also remove the whitespace from the original, before resizing to the PRISM Break size. It has over 25px of whitespace on all sides.

**Comment by mimi89999** [comment]
I removed the whitespace. I didn't notice the whitespace in the `medium` image and that it wasn't 60x60px before you told me. Sorry for not checking that before making the PR.

**Comment by mimi89999** [comment]
@Zegnat Do I need to do anything else for this PR to be merged?

**Comment by Zegnat** [comment]
Looks good to me, merging.

**Pull request merged**
