### PR TITLE
Added OsmAnd (Maps), Fixed some missing translations

### PR DESCRIPTION
**Pull request by caffeinewriter**
http://osmand.net

### CODE REVIEW

**Comment by RiQuY** [comment]
Can't find OsmAnd in F-Droid is it possible to run it without Google services like Google Play?

**Comment by Hillside502** [comment]
It's on Amazon
https://www.amazon.com/gp/product/B00D0SEGMC/ref=mas_pm_OsmAnd-Maps-Navigation

but I don't know whether it needs gapps.

**Comment by yegortimoshenko** [comment]
https://f-droid.org/en/packages/net.osmand.plus/

**Comment by Hillside502** [comment]
The direct link is good, but F-Droid's search box gives 0 result.

**Comment by RiQuY** [comment]
Do you have the repository to add to F-Droid? Thank you in advance.

**Comment by Hillside502** [comment]
The app is in the main F-Droid repo; it's just the website search that fails.

**Comment by RiQuY** [comment]
Should I download the app from F-Droid even if it is not the official upload?

**Comment by Zegnat** [comment]
> Should I download the app from F-Droid even if it is not the official upload?

Do you trust F-Droid to compile apps for you? If you are already using F-Droid, the answer to that seems to be yes. In that case, why would you not trust them with OsmAnd?

The F-Droid [repository for OsmAnd](https://gitlab.com/f-droid-mirrors/OsmAnd-submodules) is actually just links to separate official GitHub repositories from OsmAnd. So there should be no source differences between an “official upload” and the F-Droid one.

**Comment by Hillside502** [comment]
@RiQuY 
You're confusing matters by editing previous comments, instead of commenting afresh.

You slotted in https://github.com/osmandapp/Osmand/pull/4348 retrospectively.

**Pull request merged**
