### PR TITLE
Remove notes on Pidgin

### PR DESCRIPTION
**Pull request by yegortimoshenko**
This is a fixup for #1847.

### CODE REVIEW

**Comment by alerque** [comment]
This looks good –thanks for the contribution @yegortimoshenko– but I think we should rip that bit of copy out from all the locale strings at the same time. Can you tackle that too? If not I can contribute a commit that somebody can cherry pick into your branch for merging.

**Comment by yegortimoshenko** [comment]
Sure, no problem.

**Comment by strugee** [comment]
@yegortimoshenko thanks for preparing this! Just drop a note here once it's fixed for all locales and I'd be happy to merge :thumbsup:

**Comment by yegortimoshenko** [comment]
Done, now this pull request removes notes on Pidgin from all locales.

**Comment by alerque** [comment]
A least at a quick scan this looks good to me now. :+1: Thanks for doing that extra work @yegortimoshenko.

**Comment by strugee** [comment]
Thanks for this! It's gonna take me a while to work through all the pings, just as a heads up.

**Comment by yegortimoshenko** [comment]
Thanks.

**Pull request merged**
