### PR TITLE
Replace uBlock with uBlock Origin

### LINKED ISSUE #1291: uBlock Origin
https://github.com/gorhill/uBlock
https://www.youtube.com/watch?v=_D1TpddtVUA
https://github.com/gorhill/uBlock/issues/38#issuecomment-91871802
www.reddit.com/r/firefox/comments/31kk9x/ublock_creator_requests_old_project_to_be_renamed/

I don't know what to make of this, but the best we can do is list both uBlock and uBlock Origin.

EDIT: uBlock Origin seems like the better choice, especially when you consider privacy

### PR DESCRIPTION
**Pull request by vyp**
Ref #1285.
Closes #1291.

### CODE REVIEW

**Comment by Zegnat** [comment]
Isn’t this one missing some image files?

**Comment by vyp** [comment]
Couldn't find larger images (the original one is 76x76). I think @nylira is okay with it if there's only a 60x60? Because for example in #1327 I couldn't find anything larger than a 50x50 for semanticscuttle. It's possible though that there's bigger images, I don't think I checked for them that deeply.

**Comment by vyp** [comment]
Wait don't merge, I don't why I didn't find this when I made the pr: https://github.com/gorhill/uBlock/blob/master/src/img/icon_128.png

**Comment by vyp** [comment]
It's funny, I found the 76x76 in the same directory as https://github.com/gorhill/uBlock/blob/master/doc/img/ublock.svg, but did not see it??! Don't know what was going on there.

**Comment by Zegnat** [comment]
No problem, I have no problem if there legitimately aren’t any bigger pictures. Just couldn’t imagine there not being any! If you add them and rebase the commit I will merge, just ping me :smile:

**Comment by vyp** [comment]
Done.

**Pull request merged**
