### PR TITLE
SMSSecure is now Silence.

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by nylira** [comment]
Hey mimi, thanks for the update.

Please copy your changes to the other language files too.

**Comment by mimi89999** [comment]
Is it possible to do this automatically?

**Comment by mimi89999** [comment]
I guess `sed` is all I need...

**Comment by mimi89999** [comment]
@nylira Done.

**Comment by alerque** [comment]
@mimi89999 The merge commit here is somewhat extraneous and will add mess to the project if this is merged to the main project as is. Can you rebase this branch on master instead? That should this branch with just the changes you made rather than re-introducing things that already have commits in history.

If you are on the command line this should be as simple as:

    # Add a remote if you don't have it already:
    git remote add upstream https://github.com/nylira/prism-break.git

    # Fetch commits from all remotes
    git fetch --all --prune

    # Rebase your fork on the current upstream master
    git rebase upstream/master

    # Force-push your modified fork over the top of the current Github version
    git push -f origin master

**Comment by mimi89999** [comment]
@alerque I did it in a different way, but it should be OK now.

**Comment by nylira** [comment]
Thanks!

**Pull request merged**
