### PR TITLE
Add EteSync

### PR DESCRIPTION
**Pull request by tasn**
This adds EteSync, which does end-to-end encrypted contacts and calendars sync for Android.

For all I know it's the only existing project that does end-to-end.

Please review.

Thanks.

### CODE REVIEW

**Comment by Hillside502** [comment]
EteSync - Secure Journaled Sync
https://www.etesync.com/

Show HN: EteSync – Secure and journaled sync for Android | Hacker News
https://news.ycombinator.com/item?id=13975965

**Comment by tasn** [comment]
Hey,

I updated the PR to include the newly added desktop support.

**Comment by tasn** [comment]
Relevant link from reddit: https://www.reddit.com/r/privacytoolsIO/comments/7dt583/etesync_open_source_and_endtoend_encrypted/

**Comment by yegortimoshenko** [comment]
Oh, this is really good! I think we should merge it. This would also resolve #516.

**Comment by yegortimoshenko** [comment]
@strugee: could you review this? Here is a FAQ with technical details: https://www.etesync.com/faq/#glossary

Cryptography looks solid to me (the only note that it uses CBC mode, but this is compensated by HMAC).

**Comment by tasn** [comment]
@yegortimoshenko: thanks for taking a look at my PR.

I also forgot to mention that the EteSync python API was recently packaged for Arch and is now in the main repos: https://www.archlinux.org/packages/community/any/python-etesync/

Please let me know if there's anything I can do to help/clarify regarding this PR.

**Comment by Hillside502** [comment]
etesync 0.5.2 : Python Package Index
https://pypi.python.org/pypi/etesync/

**Comment by p2635** [comment]
anyone got a referral code?

**Comment by tasn** [comment]
Update: it has also been recently added to PrivacyTools.io
Link: https://www.privacytools.io/#calendar_contacts

**Comment by yegortimoshenko** [comment]
I would like some feedback on EteSync. If there isn't any, I am going to merge by myself!

**Comment by tasn** [comment]
Thanks for merging my PR. :)

**Comment by yegortimoshenko** [comment]
Thank you for writing great privacy- and freedom-respecting software.

**Pull request merged**
