### PR TITLE
Added twister microblogging platform

### PR DESCRIPTION
**Pull request by P3lUZa**
Added an experimental microblogging platform which uses the bitcoin blockchain, this pull request closes https://github.com/nylira/prism-break/issues/1167 https://github.com/nylira/prism-break/issues/828 https://github.com/nylira/prism-break/pull/1286

### CODE REVIEW

**Comment by simonasd** [comment]
hum...Some one please check this project out? 
it's becoming popular in China because Twitter is blocked and local SNSs censored seriously.

**Comment by vyp** [comment]
@simonasd on first look, it looks really good. :+1: for me. Especially when people are already using it.

**Comment by simonasd** [comment]
@vyp I'm searching information about this project.its app available in Fdroid.

BTW I just noticed that <a href='https://twitter.com/TwisterPtoP'>@Twister on twitter</a> retweet "China twister user and promoter arrested in Shanghai" days ago. And there is <a href='https://twitter.com/hashtag/FreeLoveChan'>a tag</a> about it. Much to my surprise.

**Comment by vyp** [comment]
@simonasd I saw that too. Don't associate your github account with your actual identity just in case. (Sorry for saying it here, there was no email address associated with your account, and telling you to email me has problems because this is essentially a public forum. And asking for your email here has even more problems.)

**Comment by simonasd** [comment]
@vyp thx very much. I will be much more careful from now on. 

Maybe i can creat a new PGP key and publish it on github, then we can talk safely?

**Comment by vyp** [comment]
@simonasd Yes, but be sure you are creating a new key, instead of just adding an identity to your already existing personal key (if it exists). (Just use your github username for the name of your new identity on the new key?) And use a email address that hopefully cannot be tied back to you (i.e. email address without your name in it). My public key: https://keybase.io/rws/key.asc (at least at time of writing). I'm assuming you know how to do all this?

But that was mainly all I wanted to say anyway. However, it would not hurt creating one anyway if you are willing.

**Comment by simonasd** [comment]
@vyp Ok I got it. 
thank you :)

**Comment by libres-y-salvajes** [comment]
'The assumption is that we should leave the problem of secure
    anonymizing technology implementation to the experts of the field,
    namely the Tor project <https://www.torproject.org/>, and then make
    twister to operate on top of this.
    There is one remaining problem, however, preventing twister from
    operating on top of Tor and thus allowing a more interesting threat
    model where the adversary could be a censoring government. While
    both the registration network (Bitcoin-like) and post
    storage/propagation network (BitTorrent-like) can easily be run on
    top of a Tor proxy, the DHT overlay network uses UDP protocol which
    is not supported by Tor. One possible idea thought is to connect to
    other twister nodes which have full connectivity by TCP and have
    them to relay messages to the DHT network.'


It seems it has to be run on top of Tor in order to be properly
anonymized, and there is still an unresolved issue regarding network
protocols. That is not very obviously stated on the website, though.
Perhaps that might complicate things a bit.
I think configuring protocols and proxies is a little too much if we
want to keep it easy and simple for everyone.

**Comment by vyp** [comment]
@libres-y-salvajes If I'm understanding everything correctly, they don't run on top of tor, precisely because of what you just quoted. It's good that they at least *know* that UDP over tor should not be done, unlike with ZeroNet where they just say they use tor but without *any* explanation how as far as I can see.

> That is not very obviously stated on the website, though. Perhaps that might complicate things a bit.

It's not stated because they don't, therefore it's not a problem.

> I think configuring protocols and proxies is a little too much if we want to keep it easy and simple for everyone.

Looks to me like they were talking about future development (by them), than for *users* to do it themselves.

Provided we want to keep it easy and simple for everyone, by looking at the screenshots, it looks *very* similar to the twitter.com website, which is a *good* thing. For better or for worse, familiarity plays a key role in software being "easier" to people.

The rest of the [faq](http://twister.net.co/?page_id=25) gives the right answers for me. E.g. in the "How secure is twister?" question, they talk about using encryption that was supposedly not compromised by the NSA...

Do understand though that I'm am only advocating for it with the experimental flag, because they themselves give a red beta warning, which should be enough to give the experimental flag to it.

**Comment by yegortimoshenko** [comment]
Blocked by #828.

**Pull request closed without merging**
