### PR TITLE
Remove debian comment about disabling contrib and non-free repositories

### PR DESCRIPTION
**Pull request by vyp**
See https://github.com/nylira/prism-break/issues/1709#issuecomment-323799573

### CODE REVIEW

**Comment by mimi89999** [comment]
One thing you maybe forgot about:
If the installer detects hardware that won't work with free software (usually Wi-Fi cards), it will give an option and suggest to enable non-free and contrib and to install the driver/firmware from there....

**Comment by hasufell** [comment]
Hm, I think we are in nitpicking land anyway, but if the installer already gives a warning, is that not sufficient? And if it isn't, shouldn't we suggest a fix for the debian installer (e.g. clarifying the implications) instead of adding that info to prism-break notes?

**Comment by vyp** [comment]
Well @mimi89999 said it suggests it as an option, not necessarily as a warning, to be nitpicky. And I would agree that if that's the case, maybe we could have a note warning about using that option? But if it is already a 'warning' then I don't think any further note is needed. (And I'm not sure what it is myself because I haven't installed debian in years.)

**Comment by strugee** [comment]
Did some investigation, looks like these strings are defined here: https://anonscm.debian.org/cgit/d-i/apt-setup.git/tree/debian/po/templates.pot#n471. IIRC "use {non-free,contrib} software" is the title of the message box, which has the paragraph, two newlines and the question. Then button for yes/no. Again, IIRC, no is selected by default.

**Comment by hasufell** [comment]
I think that's enough for a warning. No need for handholding.

**Comment by strugee** [comment]
@vyp can you rebase?

**Comment by strugee** [comment]
Also while you're at it maybe shorten the commit message so it's [under 50 characters](https://chris.beams.io/posts/git-commit/#limit-50); maybe

>Remove advice on disabling Debian contrib/non-free repos

would work?

**Comment by hasufell** [comment]
> under 50 characters;

🙄

**Comment by strugee** [comment]
@hasufell hm? I like a nice commit log; if it's not under 50 that's fine but it's nice to shoot for.

**Comment by hasufell** [comment]
That's arbitrary preference (and most projects I know and have contributed to have a different preference). We shouldn't bother contributors with that. It's useless.

**Comment by strugee** [comment]
@vyp ping re: https://github.com/nylira/prism-break/pull/1800#issuecomment-361105758

**Comment by yegortimoshenko** [comment]
@strugee: I've rebased it on top of master.

**Comment by yegortimoshenko** [comment]
Thanks!

**Pull request merged**
