### PR TITLE
Replace most logos with SVG counterparts

### LINKED ISSUE #1898: Automate image resource generation
Right now a bunch of manual work is involved in adding project logos at several sizes. We keep ending up with mistakes like bogus aspect ratios (e.g. #1894) and inconsistent compression etc.

I  started on some code for the build system the other day so we can just keep one higher resolution resource around for each project (much easier to find from upstream projects) and automatically generate al the sizes and scales we need for the site. This should take both the errors and trouble involved in manual image generation out of the process.

(Somebody can assign this to me, the issue is just a reminder that I'm working on it.)

### LINKED ISSUE #1980: Switch to SVG
This is an alternative to #1898.

We could just either convert or find all currently listed logos in SVG and switch to that instead of making build pipeline more complex.

https://caniuse.com/#feat=svg

### PR DESCRIPTION
**Pull request by yegortimoshenko**
Resolves #1980, closes #1898.

This pull request replaces most logos (currently, two thirds) with SVG counterparts. This pull request is huge and dependent on all other open pull requests I've sent against PRISM Break.

Quite a few logos were updated to newer versions, and all are now curated to prevent squashed icons. Also, icons shouldn't have any white margins anymore, which makes them feel more consistent.

* [x] Run `svgcleaner`

## Solve rendering issues

Some logos don't render in Firefox properly:

- [ ] `freebsd.svg`, heavy effects, some don't render (likely can't be resolved without redrawing, see http://xpam.pl/blog/?p=86)

## Trace / remake

Some logos are simple enough to be traced or remade:

- [x] https://librecmc.org/
- [x] https://github.com/Upload

## Ask upstream for SVG source

These logos are likely made in a vector editor, so it should be possible to ask for a EPS/PDF/SVG file:

- [x] https://github.com/zeapo/Android-Password-Store
- [x] https://github.com/Cookie-AutoDelete/Cookie-AutoDelete
- [x] http://ecryptfs.org/about.html
- [x] https://ejabberd.im/
- [x] https://gpgtools.org/
- [x] https://www.startpage.com/
- [x] https://github.com/kamailio/kamailio
- [x] https://kolab.org/
- [x] http://kolabnow.com/
- [x] https://github.com/kontalk/androidclient
- [ ] https://libreswan.org/
- [x] https://gitlab.metager3.de/open-source/MetaGer
- [x] https://noscript.net/
- [x] https://www.igniterealtime.org/projects/openfire/ (see https://discourse.igniterealtime.org/t/openfire-svg-logo/81956)
- [x] https://github.com/padams/Open-Web-Analytics
- [x] https://github.com/osmandapp/Osmand/
- [x] http://project-osrm.org/
- [x] https://github.com/pydio
- [x] https://subgraph.com/sgos/
- [x] https://tigase.tech/
- [x] https://www.unbubble.eu/
- [x] https://github.com/Upload
- [x] https://github.com/zenphoto/zenphoto

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
I'm not sure if this is the best way to reach out, but let me try. 

Hi! [PRISM Break](https://prism-break.org/en/projects/) lists your software, and I would like to open a pull request that replaces all logos with SVG versions. I've thoroughly looked through your repos, but couldn't find SVG/EPS/PDF logo. Could you please send me one, if available?

Cookie AutoDelete: cc @mrdokenny 
Kontalk: cc @daniele-athome 
Open Web Analytics: cc @padams
OsmAnd: cc @vshcherb
Password Store: cc @zeapo
Pydio: cc @cdujeu
Unbubble: cc @unbubble 
Zenphoto: cc @acrylian

**Comment by vshcherb** [comment]
OsmAnd: I'm afraid we only have raster - https://github.com/osmandapp/OsmAnd-misc/blob/master/logo/simple/osmand-app-512.png (old) and new https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/mipmap-xxxhdpi/icon_free.png .
CC  @dmpr0 if we can find an svg version

**Comment by acrylian** [comment]
I will look if I can find some vector versions.

**Comment by JeremyRand** [comment]
Where did you get the logo that you're using for Namecoin?  That's not our logo.  Our logo can be found at https://github.com/namecoin/namecoin-graphics/ (with SVG source).

**Comment by yegortimoshenko** [comment]
@JeremyRand: I've used https://commons.wikimedia.org/wiki/File:Namecoin_SVG.svg, but now I see it's a bit different. Replacing it with the proper version, thank you for noticing.

**Comment by cdujeu** [comment]
Hi @yegortimoshenko, the file attached should do the trick for Pydio Cells (our latest version of Pydio, a full rewrite in golang). Please link to the pydio/cells repository instead of pydio/pydio-core if possible. 
Tell me if it's ok ! 
Charles
[PydioCells.svg.zip](https://github.com/nylira/prism-break/files/2072832/PydioCells.svg.zip)

**Comment by dmpr0** [comment]
OsmAnd Logo.
[OsmAnd_Logo.svg.zip](https://github.com/nylira/prism-break/files/2080836/OsmAnd_Logo.svg.zip)

**Comment by acrylian** [comment]
Here are the Zenphoto logos. I think the button logo is the one to use on the site.
[zenphoto-cms-logos.zip](https://github.com/nylira/prism-break/files/2084653/zenphoto-cms-logos.zip)

**Comment by strixaluco** [comment]
K-9 Mail Logo
[K-9 Mail.zip](https://github.com/nylira/prism-break/files/2086590/K-9.Mail.zip)

**Comment by zeapo** [comment]
Password store logo
https://gist.github.com/shgysk8zer0/9436084ca74adef73306f06fc2b697ed#file-android-password-store-svg

**Pull request closed without merging**
