### PR TITLE
Add Privacy Badger

### LINKED ISSUE #988: add Privacy Badger
[Privacy Badger](https://www.eff.org/privacybadger) is EFF's alternative to Disconnect and Ghostery.

> Privacy Badger is a browser add-on that stops advertisers and other third-party
> trackers from secretly tracking where you go and what pages you look at on the web. 
> If an advertiser seems to be tracking you across multiple websites without your
> permission, Privacy Badger automatically blocks that advertiser from loading any
> more content in your browser.  To the advertiser, it's like you suddenly disappeared.

It differs from them because "[it] automatically analyze[s] and block[s] any tracker or ad that violated the principle of user consent".

Privacy Badger is available for Firefox and Chrome.

### PR DESCRIPTION
**Pull request by vyp**
Closes #988.

### CODE REVIEW

**Comment by Zegnat** [comment]
Should this include a note how it may be less effective than a classic blacklist-based solution? Or even expand its description?

I think the description “Privacy Badger blocks spying ads and invisible trackers” might promise too much, IMHO, as the add-on first has to learn what is and isn’t a “spying ad” and will not just block them from the first moment.

**Comment by vyp** [comment]
Sure, but to avoid waste of time, could you give me the exact description you want? (And I'll simply copy paste it if you'd like?) Because I'm not exactly sure what to say. (The current one is just copy pasted from the official website.)

**Comment by Zegnat** [comment]
I wasn’t really sure, but now that I have slept on it a night, maybe something closer to:

> Tracking blocker that tries to learn who is spying on you and then blocks these ads and invisible trackers.

Not sure how to pack this information in a single clear sentence. Tempted to use the word ‘heuristic’ but that might just confuse people further. Thoughts?

**Comment by vyp** [comment]
Heuristic is probably a good word to describe it, but as you say, it *might* confuse, so I think probably safer to go with what you suggested.

**Comment by vyp** [comment]
Hmm, I forgot about adding a note to it as well... sorry, will do so now.

**Comment by Zegnat** [comment]
No problem, thanks for all the PRs these last few days!

**Comment by vyp** [comment]
Okay, so should it say something like:

> Privacy Badger may be less effective than a classic blacklist based solution such as uBlock or Disconnect.

?

**Comment by Zegnat** [comment]
> Privacy Badger may be less effective than a classic blacklist based solution such as uBlock or Disconnect. Advertisers can automatically unblock themselves by claiming not to track you.

That last sentence might be important to some people. Privacy Badger puts faith in advertisers, people may think that faith to be misplaced. Important to know when choosing whether to use the extension or not, I feel.

**Comment by vyp** [comment]
Ah yes very good point.

**Comment by Zegnat** [comment]
Looks good :+1: Want to squash it before I merge?

**Comment by vyp** [comment]
Yep no worries.

**Comment by Zegnat** [comment]
Thanks again for all the PRs :smile:

**Comment by vyp** [comment]
Unfortunately, I'm going to become pretty "busy" again soon, but at least I took a little chunk out of the pull requested accepted tickets. Which by the way, I only just remembered even existed... actually, I might make a pr for mentioning that somewhere now..

**Pull request merged**
