### PR TITLE
Mark eCryptfs as audited

### LINKED ISSUE #1048: encfs = audited -> eCryptfs = audited
Without discussing the significance of an 10-hour audit, i wanted to mention that the guy who did the 10-hour audit of encfs (mentioned on the page) also did an 10-hour audit of eCryptfs (which is not mentioned on the page)!

See: https://defuse.ca/audits/ecryptfs.htm

### PR DESCRIPTION
**Pull request by yegortimoshenko**
Closes #1048.

### CODE REVIEW

**Comment by alerque** [comment]
:+1: for merge, at least for the EN locale. Did you check to see if other locales are pulling this data from EN if there is not a localized version? If it's not doing that then this is fine to merge, but we should also open an issue to fix it because they should be (I know this works for other project related strings, just not sure about these).

**Comment by yegortimoshenko** [comment]
You are correct, it is inherited. I've dropped changes in all locales except EN.

**Comment by alerque** [comment]
That's better, thanks. It's one thing to have a bunch on untranslated strings showing up on the built site, it's a whole 'nother thing to cram localization files full on English strings. It makes it really hard to determine what's been done and what needs doing down the road.

**Comment by yegortimoshenko** [comment]
#1048 is marked as "accepting PRs", and LGTM, so merging.

**Pull request merged**
