### PR TITLE
Fixed Chinese translation and copywriting

### PR DESCRIPTION
**Pull request by paperbag**
Fixed chinese copywriting, accounding to [sparanoid/chinese-copywriting-guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines).

### CODE REVIEW

**Comment by strugee** [comment]
@paperbag hey, sorry I missed this! There seem to be some merge conflicts here; can you rebase on top of current `master` and resolve those? Let me know if you need help with that

**Comment by paperbag** [comment]
solved!

**Comment by nylira** [comment]
Thanks!

**Comment by mimi89999** [comment]
Conflicts weren't resolved correctly. Merging this PR made a mess in git!

**Comment by paperbag** [comment]
Sorry for my carelessness.
I didn't notice that duckduckgo was removed.
I think that i should pull request again to solve my error.
#edit: https://github.com/nylira/prism-break/pull/1714

**Pull request merged**
