### PR TITLE
Add Cloudron project

### PR DESCRIPTION
**Pull request by nebulade**
This contains one commit which only fixes trailing whitespace. I am not sure if this is wanted, if not, I will remove that commit.

Thanks.

### CODE REVIEW

**Comment by strugee** [comment]
Hi, thanks for your PR. I don't recall Cloudron being discussed before; is that correct? If so we'd need to evaluate it before this can be merged.

Thanks for contributing to PRISM Break.

**Comment by gramakri** [comment]
@strugee I am one of the co-founders of cloudron.io. Let me know if you have any questions. The best place to start is https://cloudron.io/get.html#selfhost. You can also see the demo at https://my-demo.cloudron.me.

**Comment by nebulade** [comment]
@strugee is there any document on what the criterias for being accepted in the project list are? 

From the main Readme it looks like being an open source project is one of the main points (Cloudron is AGPLv3). Additionally from a project vision standpoint, I think Cloudron is largely aligned with your statement in the `Quality over quantity` point, focusing on allowing to stay in control of data together with providing ease of use. (see top of the page https://cloudron.io/features.html)

**Comment by strugee** [comment]
@nebulade https://github.com/nylira/prism-break#project-inclusion-guidelines is the official project inclusion guidelines. However I think that list could do with a rewrite... it doesn't really make it clear to what extent we still value security. For a very clear-cut example take #1310 where we rejected Icecat because it wasn't able to keep up with upstream security patches.

I'll open an issue to formalize this and correct the list I linked to above, but broadly in terms of security we're looking for projects that:

* Understand security and take it seriously (this is very broad, but can range from "don't invent your own crypto" to "think about and design against metadata leaks")
* Offers security advantages that other projects don't (this is why e.g. Sandstorm's containerization model is particularly interesting to us)
* Can keep up with security events
* Doesn't depend on, imply or promote insecure things including and especially things in the "proprietary" column

This list is non-exhaustive, though, and we should really fix the above link.

**Comment by Hillside502** [comment]
@strugee 
Cloudron is tied to
`Ubuntu 16.04 (Xenial)`
https://cloudron.io/references/selfhosting.html#installing

How does this fit with PRISM Break's Ubuntu exclusion --- such as #1463 #1471 ?

**Comment by strugee** [comment]
@gramakri is Cloudron actually tied to Ubuntu? Or is it just a recommendation, not a requirement?

If it's the former, we can't list it on PRISM Break. We've rejected projects before because they require rejected dependencies (the perennial example being Signal).

**Comment by gramakri** [comment]
@strugee Yes, Cloudron requires Ubuntu 16.04 Sever.

**Comment by strugee** [comment]
@gramakri that's too bad. Unfortunately we can't list Cloudron in that case since we've previously rejected Ubuntu from the list.

**Comment by nebulade** [comment]
That's too bad. Is the rejection still holding up, given the comments in https://github.com/nylira/prism-break/issues/1471 as well as I assume there is much difference between the desktop and the server version?

**Comment by Hillside502** [comment]
@nebulade 
Looking at:-
Server and Desktop Differences - Preparing to Install - Ubuntu Server Guide
https://help.ubuntu.com/16.04/serverguide/preparing-to-install.html#intro-server-differences

"There are a few differences between the Ubuntu Server Edition and the Ubuntu Desktop Edition. It should be noted that **both editions use the same apt repositories**..."

"Ubuntu no longer has separate -server and -generic kernel flavors. These have been **merged into a single -generic kernel flavor**..."

So, please consider an additional (or replacement) OS from:-
Servers - Platforms - PRISM Break
https://prism-break.org/en/categories/servers/#operating-systems

of course, reduced to a subset as available on cloud infrastructure providers, especially --- my favourite, the Swiss-located Exoscale.

Simple cloud computing for cloud native teams | Exoscale
https://www.exoscale.ch/

How Exoscale compares to DigitalOcean and Amazon
https://www.exoscale.ch/compare/

**Comment by nebulade** [comment]
I understand your position here. It is however unlikely that we will officially support any other distribution in mid term, given the additional maintenance and testing effort required. I will come back to this pull request once we do. Thanks.

**Comment by strugee** [comment]
@nebulade PRISM Break has not yet made a decision regarding Ubuntu, so this rejection still stands. If we ever add Ubuntu to the list again then I'd be happy to reopen this PR.

**Pull request closed without merging**
