### PR TITLE
Added Web Pizza Project

### PR DESCRIPTION
**Pull request by rpgeeganage**
Web Pizza is tool which I developed to share files through TOR. The main idea is taken from Onion Share. The main feature is remote file support.

### CODE REVIEW

**Comment by merlinnusr** [comment]
link ?

**Comment by mastercoms** [comment]
https://github.com/rpgeeganage/web-pizza-file-share/ in the changes

**Comment by rpgeeganage** [comment]
Hi,
[https://github.com/rpgeeganage/web-pizza-file-share/](url) contains the source.
In addition http://secu.link contains few other tools.

thanks.

**Comment by Zegnat** [comment]
I am not sure what this does… it allows me set-up a password that will then show someone links to external resources? I would just put those links in an email, personally, but maybe I am not the target demographic. Anyone have any thoughts on the usefulness of this?

@rpgeeganage you might also want to put a real licence on the project. What you currently have is called an [informal license](https://www.gnu.org/licenses/license-list.en.html#informal) and is just hard to work with:

> If you want your code to be free, don’t invite gratuitous trouble for your users. Please choose and apply an established free software license.

In the spirit of letting users do “whatever”, the FSF recommends using [CC0](https://creativecommons.org/about/cc0/) or [Unlicense](http://unlicense.org) (both GPL compatible) to pledge your work to the public domain.

**Pull request closed without merging**
