### PR TITLE
Added SignaliOS

### PR DESCRIPTION
**Pull request by plastipeta**

### CODE REVIEW

**Comment by TheMSB** [comment]
I'm just curious after seeing the discussion going on in #1239 and #552 
From what I understand of OpenWhisperSystem's software is that Signal is pretty much a merger of TextSecure and Redphone but then on iOS. The mentioned apps were both excluded from PRISM-break's list because they rely on proprietary software(play services).

Since I am not an expert in OpenWhisperSystem's software, even if Singal on iOS uses proprietary software from Apple to deliver push notifications, wouldn't the use of Signal still be better than using plains SMS and phone calls? Seeing as you already 'trust' iOS.
(just trying to get a better understanding here)

**Comment by vyp** [comment]
@TheMSB I guess the potential for danger here is if the push notifications have access to the content (i.e. text message content)? I don't suppose it would because that sort of defeats the purpose of end to end encryption I think. So if none of the services provided by the OS have access to the actual content, yes I do think it should be better.

The key difference between iOS and android is that iOS is proprietary, so one point or another in the stack, you're going to need to trust iOS anyway (almost making using iOS a lost cause for privacy for me). And so the reason to reject the usage of proprietary play services in android apps is that we know we can do better, but with iOS we cannot really.

**Comment by Zegnat** [comment]
> And so the reason to reject the usage of proprietary play services in android apps is that we know we can do better, but with iOS we cannot really.

Another big reason is that Android applications that make use of proprietary libraries (and/or Google services) might not work on alternative operating systems like Replicant. PRISM Break recommends people use these to avoid possible security holes already, so recommending software that doesn’t run on those OS at all would be weird.

**Comment by TheMSB** [comment]
Are there any objections left to this PR or #1392 (the iOS portion at least)?

**Comment by Sigmun** [comment]
What I don't understand on this discussion is that it seems to be a problem that Signal use iOS which is not trustable so it cannot be recommended. But then, why TextSecure for instance is recommended ?

**Comment by strugee** [comment]
@Sigmun ChatSecure is also (was also?) available on F-Droid on Android.

**Pull request closed without merging**
