### PR TITLE
Remove Ubuntu notice

### LINKED ISSUE #1471: Will Ubuntu/Derivatives be considered again after the 16.04 update?
Since Ubuntu 16.04 is disabling it's spyware by default on it's upcoming version 16.04, will Ubuntu or its derivatives be considered then?
I'd argue that Linux Mint, and the other Ubuntu derivative should be considered again after 16.04, because they provide good security through encryption. They provide an easy way for beginners to encrypt their systems. I don't think Ubuntu's packages outside of Unity contain any spyware myself. Trisquel is based on Ubuntu, and is endorsed by FSF/GNU. The FSF/GNU is arguably more concerned about free software than us, and they endorse Trisquel. Issue #642 claims that Linux Mint connects to many different domains, and it does. Because Linux Mint automatically checks for updates, so Mint connecting to so many domains would be expected.
I think this list needs a true beginners distribution. Not even Fedora is a true beginners distribution. Will the tech illiterate looking at this list try something difficult, or just keep running Windows/OSX?
Proof: http://www.pcworld.com/article/3015021/linux/ubuntu-1604-lts-wont-send-local-searches-over-the-web-by-default.html

### PR DESCRIPTION
**Pull request by yegortimoshenko**
Resolves #1471. Ubuntu does not come with spyware since 16.04, [which is the current LTS version](https://www.ubuntu.com/download/desktop), and new installs are unlikely to use older versions. That means the notice can be safely discarded.

### CODE REVIEW

**Comment by alerque** [comment]
This does not resolve that issue. Just because a couple guys comment saying something should happen doesn't mean that's the concurrences.  See earlier in the thread such as [here](https://github.com/nylira/prism-break/issues/1471#issuecomment-167903593) for why we're still not really considering this. Ubuntu still is driven largely by corporate sponsorship rather than the developer community and has burned us several times. Most of us aren't up for trusting them again yet and no serious evidence that we should do so has been forwarded on that thread.

Because we are not listing them as a recommendation, we get a constant barrage of suggestions to include it. Since we don't otherwise have a rejected projects list yet, The warning notice is there as reminder that it has been considered. And I think for now it should stay.

**Comment by alerque** [comment]
Yes, I could see rewriting it a little. It  should also link to a more relevant issue, the one it's linked to doesn't have the lastest or bulk of the discussion.

**Comment by hasufell** [comment]
Yes, it always has been primarily a trust issue.

**Comment by yegortimoshenko** [comment]
OK, this will need another iteration.

**Pull request closed without merging**
