### PR TITLE
Redmatrix >> Hubzilla

### PR DESCRIPTION
**Pull request by jeroenpraat**
Redmatrix is defunct. The successor is Hubzilla.

### CODE REVIEW

**Comment by nylira** [comment]
Thanks!

**Comment by jeroenpraat** [comment]
You're welcome! When will prism-break.org be updated?

**Comment by nylira** [comment]
In a couple hours or so!

On Wednesday, December 9, 2015, Jeroen van Riet Paap <
notifications@github.com> wrote:

> You're welcome! When will prism-break.org be updated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nylira/prism-break/pull/1451#issuecomment-163207663>.
>


-- 
Peng Zhong
Interaction Designer & Developer

Designer at http://nylira.com
Curator at https://prism-break.org
GitHub: https://github.com/nylira
LinkedIn: https://www.linkedin.com/in/nylira

**Comment by jeroenpraat** [comment]
Great!

**Pull request merged**
