### PR TITLE
Remove TorChat [1] and add Ricochet [2] in its place

### LINKED ISSUE #957: TorChat development appears stagnant, Torsion offers maintained alternative
The last commits for Torchat seem to be from 2012 according to their Github page and there hasn't been any official announcements since then.

There is an alternative called Torsion (https://github.com/special/torsion) that appears to offer the same basic features and user experience, and it's also currently being maintained.

### LINKED ISSUE #1083: Torchat is no long maintained
My understanding is that TorChat is no longer maintained and may be unsafe to use. Ricochet (https://github.com/ricochet-im/ricochet) is an offshoot of TorChat. Should TorChat be substituted by Ricochet on the Prism-Break list?

### LINKED ISSUE #1152: How about ricochet im ?
I think that will be good project 

https://github.com/ricochet-im/ricochet

### PR DESCRIPTION
**Pull request by vyp**
Closes #957.
Closes #1083.
Closes #1136.
Closes #1152.

[1]: https://github.com/prof7bit/TorChat
[2]: https://github.com/ricochet-im/ricochet

---

@plastipeta's #1136 pull request has merge conflicts, so here's an updated one.

I feel comfortable with removing TorChat because:

1. Latest commit is January 2014 (considering all branches) and latest release
   is 2012.
2. There's already many applications in the Instant Messaging category.
3. There's Ricochet to take its place.

I think Ricochet *should* be added because I it's p2p, which there isn't much
of in the category, and of course p2p removes a whole "server" vector
completely. (And it's actively maintained.)

Only my opinions though of course.

### CODE REVIEW

**Comment by vyp** [comment]
Btw, Torsion mentioned in #957 is now known as Ricochet.

**Comment by vyp** [comment]
Ugh, just seen a typo, do not merge yet!

**Comment by vyp** [comment]
Typo fixed.

**Comment by nylira** [comment]
Thanks!

**Pull request merged**
