### PR TITLE
Add uMatrix (Firefox addon)

### PR DESCRIPTION
**Pull request by geplus**
https://addons.mozilla.org/it/firefox/addon/umatrix/?src=dp-dl-othersby

"Point & click to forbid/allow any class of requests made by your browser. Use it to block scripts, iframes, ads, facebook, etc."

 GNU General Public License, versione 3.0

I think it shares part of its code with uBlock

### CODE REVIEW

**Comment by vyp** [comment]
Hmm, the diff is huge... I'm not sure but it says you want to merge into the 0.1.0 branch instead of what I think should be the master branch. Can you confirm?

**Comment by Zegnat** [comment]
I seem to recall earlier discussions on this where it was decided that uMatrix was such a power-user tool that we were more inclined to recommend RequestPolicy instead. Can’t find any links right now though. Thoughts?

**Comment by vyp** [comment]
@Zegnat You are correct, discussion was in #1299. I agree with gorhill that uMatrix is for advanced users, but perhaps we could still recommend and give it a warning in the notes section? (btw, requestpolicy is already recommended on the site, if you meant one or the other.)

**Comment by vyp** [comment]
@Zegnat Also, this unrelated, but this reminds me, we probably want to update requestpolicy to https://github.com/RequestPolicyContinued/requestpolicy/ as @nodiscc said. What do you say?

**Comment by Zegnat** [comment]
800a30d mentions uMatrix as a more advanced alternative to Request Policy. I think I am going with that for now.

**Comment by geplus** [comment]
Can you mention it as an alternative to request policy in the Web Browsers Addons section?

**Comment by Zegnat** [comment]
@geplus, that is exactly what I did in 800a30d. You can see I added the following to `web-browser-addons-notes`:

```
<p>A more advanced alternative to <strong>Request Policy</strong> would be <a href='https://github.com/gorhill/uMatrix'><strong>uMatrix</strong></a>.</p>
```

The change will go live at the next update.

**Comment by geplus** [comment]
OK, thank you!

**Pull request closed without merging**
