### PR TITLE
Update Metronome metadata

### PR DESCRIPTION
**Pull request by yater**
broken link replaced (only for the english content (TODO must be changed for all languages))

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
Thanks. I will make this change in all files on merge.

**Comment by strugee** [comment]
@yegortimoshenko can you instead push a commit to this branch so we can all review?

**Comment by yegortimoshenko** [comment]
That's what I was going to do! :-)

**Comment by yegortimoshenko** [comment]
I've merged this patch as part of #1929. Thanks!

**Pull request closed without merging**
