### PR TITLE
Drop Disconnect

### PR DESCRIPTION
**Pull request by yegortimoshenko**
Disconnect comes with nonfree software: https://github.com/disconnectme/disconnect/issues/366

Repository has seen very little activity since 2015 (4 commits total): https://github.com/disconnectme/disconnect/commits/master

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
cc @davidhedlund

**Comment by Zegnat** [comment]
I believe the Disconnect blocking list has been adapted and is supported by a number of actually free blockers now? I see no real reason why we need to recommend Disconnect alongside other blockers at this point.

**Comment by yegortimoshenko** [comment]
@Zegnat I believe so, too.

**Comment by davidhedlund** [comment]
Thanks.

**Pull request merged**
