### PR TITLE
Adopt a Code of Conduct for project participants

### PR DESCRIPTION
**Pull request by alerque**
PRISM-Break is largely driven by community participation in discussions
surrounding the inclusion or exclusion of various solutions. Given that
user privacy is (by definition) a very personal matter and that the
security community in general tends to have strong opinions, my
observation is that many issues that come up are fairly highly changed
even before somebody looses their cool or makes a nasty remark.

I think it would behoove the project to officially adopt a Code of
Conduct document that can be considered binding on participants in
discussion. Getting this into the repository early before any particular
major issue between participants comes up gives everybody something to
reference and a relative standard by with to judge a situation. This
could potentially save some grief vs. the possibility of working out the
details of such a code in the middle of a disputed discussion.

The Open Code of Conduct seems like a likely candidate. I'm not a huge
fan of some of the items as worded but for this project I think it will
be fine. See http://todogroup.org/opencodeofconduct/ for details.

### CODE REVIEW

**Comment by hasufell** [comment]
#1255

**Comment by hasufell** [comment]
I think no one is going to read that wall of text.. we need a few concise and expressive bullet points on the front page.

**Comment by alerque** [comment]
@hasufell I agree that not everybody will read this up front, but then again the thing that is in the CONTRIBUTING.md document per this suggestion is just a one liner saying that there _IS_ a code of conduct. I believe this is the key feature. Most people aren't going to even need to read this because they behave decently enough anyway, but just the one liner in the file noting that there is such a thing should put those who do see it on notice that they should behave professionally and tip any would be cranks off that this project might not be the best place to act up. What specifically the points are is less important at that stage.

The other use it serves is when a specific issue does come up, and this is where having the somewhat more verbose edition around should prove to be a good thing. If something does happen there won't be a need to argue about what is or isn't appropriate, there is already a basic outline is and you can point out the relevant point and move on. This saves accusations of making up the rules as you go along or them being a matter of interpretation (they still are of course, but much less so than if it was a more general and less detailed outline).

**Comment by strugee** [comment]
+1, this is long overdue. <3

**Pull request merged**
