### PR TITLE
Refresh Firefox mobile metadata

### PR DESCRIPTION
**Pull request by strugee**
WIP, do not merge - this diff is large (because my sed commands were aggressive) and I _have not read it yet_.

Remove a bunch of duplicated Mozilla stuff and sync up the source code link with desktop Firefox.

### CODE REVIEW

**Comment by strugee** [comment]
Okay, actually read the diff now ;)

Looks okay if anyone wants to review.

**Comment by vyp** [comment]
@strugee Hmm just a friendly heads up to say that there seems to be merge conflicts here now. FWIW, I was reviewing this yesterday a bit and there weren't any merge conflicts.

**Comment by strugee** [comment]
@vyp rebased!

**Comment by vyp** [comment]
FYI I'll hopefully review this some more this weekend (if no one else does). I trust that this PR should be good because it's from you, but because you said you made some 'aggressive' sed commands, I feel like it should be properly reviewed. (It shouldn't take long, I just haven't had the time. :confused: ) OTOH, esp if I take too long, if you can find the time to double check this yourself and you're happy with it, of course feel free to merge it yourself! :smiley:

**Comment by strugee** [comment]
@vyp it took me a while to review it actually; it's 600+ lines :D

I feel pretty confident there's nothing problematic in there so if you don't find the time, I think it's okay to just merge :thumbsup:

**Comment by vyp** [comment]
That sounds good with me! Merging.

**Pull request merged**
