### PR TITLE
added conversations (XMPP Android app)

### LINKED ISSUE #1145: [XMPP] Conversations
https://github.com/siacs/Conversations

This app seems to be a great alternative for Xabber and ChatSecure.

Also available via F-Droid:
https://f-droid.org/repository/browse/?fdid=eu.siacs.conversations

### PR DESCRIPTION
**Pull request by sedrubal**
closes #1145 and possibly #1203

### CODE REVIEW

**Comment by sedrubal** [comment]
contains english and german translation and the logo ;)

**Comment by sedrubal** [comment]
Now it also contains the English data in all language dbs I can't speak ;)

Maybe it might be a good idea, if your `Makefile` could do this automatically...

**Comment by nylira** [comment]
Maybe it might be a good idea, if your Makefile could do this automatically...

This would be a good idea, just haven't figured out the best way to propagate changes across all the files with subsequent edits.

**Comment by sedrubal** [comment]
Thank you for merging.

As it is json you could make a python or js script which reads the data, compares the English version with the other languages (maybe only the project names) and if there is missing a project, it copies the data to the other language and dumps the json to the file

**Pull request merged**
