### PR TITLE
Add pass.

### PR DESCRIPTION
**Pull request by mwleeds**
Pass is a simple password manager and pretty much all you need to depend on is a Unix-like command line with GPG installed.

### CODE REVIEW

**Comment by nylira** [comment]
Thanks!

**Comment by themsay** [comment]
How about PasswordStore port of Pass made for Android user?

You can check it out from F-Droid platform, very useful password manager that work well Openkeychain in place of GPG.

**Comment by Hillside502** [comment]
For "PasswordStore" read "Password Store"

F-Droid
https://f-droid.org/repository/browse/?fdfilter=PasswordStore&fdid=com.zeapo.pwdstore

Please note beta status.  Same versions on both F-Droid and Google Play.

Password Store (beta) – Android Apps on Google Play
https://play.google.com/store/apps/details?id=com.zeapo.pwdstore

**Comment by mwleeds** [comment]
I use that app and it works well. @zeapo

**Pull request merged**
