### PR TITLE
Drop GNUnet

### PR DESCRIPTION
**Pull request by yegortimoshenko**
The project is practically dead. The latest release dates back to 2014, there has been zero activity in the repositories in the last 14 months: https://gnunet.org/git/

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
I would like to go ahead with this unless anyone minds.

**Comment by strixaluco** [comment]
I see that GNUnet projects repos are more than just alive: https://gnunet.org/git/?s=idle
Note the ```Idle``` column.
[Main repo](https://gnunet.org/git/gnunet.git/log/) reveals dozens of commits daily.

**Comment by yegortimoshenko** [comment]
@strixaluco: Hm, why https://gnunet.org/git/ doesn't show those repos? This is the URL everyone links to.

**Comment by strixaluco** [comment]
It does, but it links to umbrella project. We can change the URL to `https://gnunet.org/git/gnunet.git/log/` at least at PRISM Break.
By the way, https://prism-break.org/ seems to be down ATM.

**Pull request closed without merging**
