### PR TITLE
Fix Autistici hyperlink

### PR DESCRIPTION
**Pull request by Evanito**
The current link is a 404, my change fixes that.

### CODE REVIEW

**Comment by vyp** [comment]
Thank you. While we're at it, could you make it https://www.autistici.org/ instead?

**Comment by Evanito** [comment]
The `/en/` didn't change anything functionally and I opted to keep it because it was specifically listed under the en list.

**Comment by vyp** [comment]
Yeah I saw, I would have opted to keep `/en/` if the other locales were also linkable statically, instead of being managed by javascript, meaning that all the other languages just point to `#` and you have to click for them after reaching the site. Also I want it to be a https link if you could. :+1:

**Comment by Evanito** [comment]
Didn't notice that the first time.

**Pull request merged**
