### PR TITLE
Add Subgraph OS wrt #1703

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by hasufell** [comment]
Hello

**Comment by hasufell** [comment]
Can someone explain to me why this PR is being ignored for almost a year now?

**Comment by alerque** [comment]
I realize you called out the issue in the title, but since Github doesn't link that, having a PR description with a link would help. For reference the discussion for this issue is at #1703 ... current status is the issue was tagged as blocked pending source releases. I would suggest finishing up the discussion including @strugee's points over there in the issue instead of here in the PR.

**Comment by hasufell** [comment]
> current status is the issue was tagged as blocked pending source releases.

The sources are released. There was only FUD in the thread.



> Qubes is probably better

I don't see how that is relevant. Qubes is still listed. SubgraphOS has a clear security/privacy focus. Way more than debian.

**Comment by strugee** [comment]
@hasufell responded to in https://github.com/nylira/prism-break/issues/1703#issuecomment-363870815 to keep things centralized.

**Comment by alerque** [comment]
@strugee I've had a couple reads through the comment snafu over licensing now as well as reviewing where the project is at (not super in depth, but generally poking around) and this has a 👍 for merge from me, for whatever that's worth.

**Comment by strugee** [comment]
LGTM although I think we should add the Experimental label? subgraph.com says it's alpha

**Comment by alerque** [comment]
Yes, an experimental tag until upstream starts branding their releases as something other than alpha is probably a good move. I don't always put a lot of stock in that, some projects tag stable releases long before they  should be considered so and others wait years after they are rock solid to drop the label (looking at you KeepassX), but in this case at least for a while that sounds fair.

**Comment by hasufell** [comment]
https://github.com/nylira/prism-break/pull/1738/files#diff-1d65ca0b1886a69e5ab16eaaa239e441R3 is this not the experimental tag?

**Comment by strugee** [comment]
@hasufell wow, I feel very dumb. Nice catch, LGTM.

**Pull request merged**
