### PR TITLE
Add Discord to the list of proprietary software

### LINKED ISSUE #1670: Add Discord to the list of proprietary software
It could be added to the Instant Messaging and Video & Voice categories. Millions of people use it these days, but it's [not open source](https://www.reddit.com/r/discordapp/comments/43z4yh/open_source_protocol_encryption_privacy/cznvmxl/).
Moreover, the [Privacy Policy](https://discordapp.com/privacy) states: "Information we collect may include but not be limited to username, email address, and **any messages, images or other content you send via the chat feature**."

### PR DESCRIPTION
**Pull request by vyp**
Closes #1670.

### CODE REVIEW

**Comment by strugee** [comment]
@vyp I'm assuming you checked this out locally? I'm on mobile so I can't do it myself. LGTM though.

**Comment by vyp** [comment]
Oh no, I haven't! Sorry I should have mentioned that, it's been a while. I'm on a small laptop at the moment and don't really have the resources (i.e. time and disk space) on it to install everything and build it (I won't have access to anything else for a quite a while). I'm happy to wait until this can be tested by someone else though of course.

**Comment by strugee** [comment]
@vyp fyi, just rebased on top of `master` and force-pushed to this branch, since the zh-TW build was failing in this branch.

**Comment by vyp** [comment]
Thanks!

**Comment by strugee** [comment]
LGTM; merging

**Comment by strugee** [comment]
Thanks @vyp! :thumbsup:

**Pull request merged**
