### PR TITLE
Move CyanogenMod to proprietary section

### PR DESCRIPTION
**Pull request by hasufell**
https://github.com/nylira/prism-break/issues/654
https://github.com/nylira/prism-break/issues/723
https://github.com/nylira/prism-break/issues/726
https://github.com/nylira/prism-break/issues/903
https://github.com/nylira/prism-break/issues/1005

### CODE REVIEW

**Comment by nylira** [comment]
Thanks!

**Comment by Alexay** [comment]
@nylira Are you guys sure you're not mixing up the community-developed free and open source CyanogenMod with CyanogenOS? The links provided in those issues all pertain to CyanogenOS.

**Comment by hasufell** [comment]
see http://redmine.replicant.us/boards/33/topics/1041

**Comment by Alexay** [comment]
@hasufell that was 3 years ago. They have since separated the proprietary version into CyanogenOS and kept CyanogenMod free and open.

**Comment by Hillside502** [comment]
Commercialization controversy - CyanogenMod - Wikipedia, the free encyclopedia
https://en.wikipedia.org/wiki/CyanogenMod#Commercialization_controversy

**Comment by hasufell** [comment]
> They have since separated the proprietary version

I don't see any information that CyanogenMod stopped using/shipping proprietary drivers. And wikipedia also clearly states:

> Replicant is a CyanogenMod fork that removes all proprietary software and drivers and thus avoids all aforementioned legal issues. However, Replicant does not support devices which depend on proprietary drivers, which is most phones as of 2016.

**Comment by mimi89999** [comment]
@hasufell 
> I don't see any information that CyanogenMod stopped using/shipping proprietary drivers (which would render it as useless as replicant).

Yes, it does. As half of the GNU/Linux distribution, that prism-break is recommending. Where is the logic? I don't understand that...

**Comment by hasufell** [comment]
> As half of the GNU/Linux distribution, that prism-break is recommending. Where is the logic? I don't understand that...

huh, ever heard of kernel deblobbing? Some distros we recommend do that per default (Parabola I believe), others allow it rather easily (Gentoo, ArchLinux). And: deblobbing is a script you can use on any linux distro prior to building your kernel. Can you point me to a similar technique on Android?

**Comment by mimi89999** [comment]
@hasufell 
> ever heard of kernel deblobbing?

Yes, Linux-libre has a script for that...

> Some distros we recommend do that per default 

Yes, some do (Debian, Fedora, gNewSense, Parabola) and other don't.

> And: deblobbing is a script you can use on any linux distro prior to building your kernel. Can you point me to a similar technique on Android?

Theoretically you could run the Linux-libre script searching for blobs, remove them and rebuild the kernel with Cyanogenmod, but nobody would do that since without them and proprietary drivers and firmware, the device would be a brick.

Also, let's take as an example OpenSuse, that you recommend. It has both, free and proprietary software, firmware, drivers in it's repos...

**Comment by hasufell** [comment]
> Theoretically you could run the Linux-libre script searching for blobs, remove them and rebuild the kernel with Cyanogenmod, but nobody would do that since without them and proprietary drivers and firmware, the device would be a brick.

What? That's not even the same kernel.

**Pull request merged**
