### PR TITLE
Kompowiec's changes

### PR DESCRIPTION
**Pull request by strugee**
Somehow botched the force-push on #1665, so I'm just resubmitting. @vyp if you could review this? Basically just the changes you mentioned in https://github.com/nylira/prism-break/pull/1665#issuecomment-318642971.

### CODE REVIEW

**Comment by strugee** [comment]
> since they got wiped out

By this PR?

**Comment by vyp** [comment]
Oh no I meant that they got wiped out in #1665 so couldn't confirm if these are the same as those. Anyway, I think it should be fine to merge now. @kompowiec Let us know if there were any mistakes here. And again, thank you!

**Comment by kompowiec** [comment]
I think so is good, doesn't seen mistakes.
Also thank you, You did it better than me.

**Pull request merged**
