### PR TITLE
Drop note about FISH

### PR DESCRIPTION
**Pull request by alerque**
See note on #1852 about whitespace commit. I can rebase this easily if/when it becomes a merge conflict, just ping me.

### CODE REVIEW

**Comment by alerque** [comment]
Okay, I'll update with that in mind.

**Comment by strugee** [comment]
@alerque thanks so much :tada:

**Comment by alerque** [comment]
@strugee I rebased this and then dropped all the empty note fields in project files except for the English one. I figured if this logic was sound about pass-through to EN if no translation present it must work for all listings right? If I'm missing something there let me know.

**Comment by strugee** [comment]
> I figured if this logic was sound about pass-through to EN if no translation present it must work for all listings right?

Yeah, if there's _any_ key missing for a given project, it will fall back to the English data for that particular key. Dropping all the empty ones sounds like a great plan.

**Comment by alerque** [comment]
@strugee In that case shouldn't we drop _all_ the empty keys in translation files, not just `notes` fields? I actually did this originally and then second guessed myself and backed off to just notes for this PR. If we want all of them gone I'll submit that.

**Comment by strugee** [comment]
Ah yeah, that sounds great.

**Pull request merged**
