### PR TITLE
Added FileCast

### PR DESCRIPTION
**Pull request by onyxbits**

### CODE REVIEW

**Comment by mastercoms** [comment]
This project seems like it is in its early stages, it was started 3 days ago and has 6 commits.

**Comment by onyxbits** [comment]
It is fully functional. It has only 6 commits because I created the repo late.

**Comment by mastercoms** [comment]
Ah, sorry about the confusion and presumptions, then.

**Comment by Zegnat** [comment]
This looks like a really interesting and cool tool. But I am not sure what sort of proprietary software this is supposed to be replacing. Instead, it just seems to be a cool little open-source tool. @onyxbits, why do you believe this should be featured on PRISM Break? Maybe I’m missing something.

I am also a bit wary of featuring what is basically a web server when it doesn’t have HTTPS support.

**Comment by onyxbits** [comment]
FileCast is meant as a replacement for services like dropbox or imgur. The whole idea is to keep files you want to transfer in your local network. A typical usecase would be a friend coming over and wanting to grab some of your files, but neither of you is particularly keen on setting up any kind of cloud syncing.

I would argue that your WLAN is probably not infiltrated, so HTTP is as safe as any network share you might have setup. Nevertheless, HTTPS is on the wishlist. I just didn't have the time to squeeze it in with v1.0

**Comment by yegortimoshenko** [comment]
FileCast has last been updated three years ago: https://github.com/onyxbits/filecast

Seemingly, safe to close.

**Comment by alerque** [comment]
Agree, this doesn't fit the bill.

**Pull request closed without merging**
