### PR TITLE
Remove preconfigured servers

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by strugee** [comment]
@hasufell mind if I push a commit or two to your branch finishing this?

**Comment by strugee** [comment]
Whoops, wrong PR, sorry.

**Comment by vyp** [comment]
Looks like this is leftover from #1709.. LGTM, merging.. Thank you @hasufell!

**Comment by hasufell** [comment]
Uhm, I don't really know if this was sanctioned to be merged. Afair there was outstanding discussion, or not?

**Comment by vyp** [comment]
Oh really?? Oh my bad I can revert! yikes

**Comment by vyp** [comment]
Oh wait before I do, I just had a quick look and couldn't find anything apart from your mention of it in #1709.. was there anything else you were referring to?

**Comment by vyp** [comment]
Ok so actually I'd prefer not to revert if this was something no one really had any objections with? @strugee Do you have any opinions on this?

**Comment by vyp** [comment]
(Unless you want me to revert @hasufell. Sorry for the spam.)

**Comment by strugee** [comment]
Sorry! Guess this dropped off my review queue somehow.

Anyway, this doesn't remove the localizations from the relevant files. I think it also misses moving some assets but I'd have to double-check. That being said on principle I do want to see this change happen.

**Comment by vyp** [comment]
> That being said on principle I do want to see this change happen.

Great, I'll leave as is then until anyone else says something. I'll be more careful in the future before merging.

> Anyway, this doesn't remove the localizations from the relevant files.

I believe I've done that separately in 615e3a9. Although not sure what assets you're talking about so yeah please check that if you can. This PR has deleted the relevant logo files if that's what you mean.

**Pull request merged**
