### PR TITLE
Update Qubes URLs

### LINKED ISSUE #1830: Qubes URL redirects to https://www.qubes-os.org/
Main URL listed in prism-break database is no longer active, it redirects to https://www.qubes-os.org/ and other (like project license are straight 404's)

### PR DESCRIPTION
**Pull request by mimi89999**
Closes #1830

### CODE REVIEW

**Comment by mimi89999** [comment]
@nylira Please review.

**Comment by mimi89999** [comment]
@strugee Please merge as-is.

**Comment by mimi89999** [comment]
Can this PR get merged?

**Comment by mimi89999** [comment]
@strugee I removed the duplicated entries.

`for file in *-projects.json; do line=$(grep -n "Fedora/Xen-based OS designed to provide strong security through isolation." $file | cut -f1 -d:); line=$(($line - 2)),$(($line + 32)); sed -i -e "$line"'d' $file; done`

**Comment by strugee** [comment]
@mimi89999 so sorry I missed this! Haven't been checking my GitHub notifications as frequently during thanksgiving break. Thanks for doing this!

**Pull request merged**
